export const FORMULARIO_VEHICULO = "FORMULARIO_VEHICULO";
export const OBTENER_VEHICULOS = "OBTENER_VEHICULOS";
export const AGREGAR_VEHICULO = "AGREGAR_VEHICULO";
export const VALIDAR_FORMULARIO = "VALIDAR_FORMULARIO";
export const VEHICULO_ACTUAL = "VEHICULO_ACTUAL";
export const ELIMINAR_VEHICULO = "ELIMINAR_VEHICULO";
export const VEHICULO_ERROR = "VEHICULO_ERROR";

export const MOVIMIENTOS_VEHICULO = "MOVIMIENTOS_VEHICULO";
export const AGREGAR_MOVIMIENTO = "AGREGAR_MOVIMIENTO";
export const VALIDAR_MOVIMIENTO = "VALIDAR_MOVIMIENTO";
export const ELIMINAR_MOVIMIENTO = "ELIMINAR_MOVIMIENTO";
export const MOVIMIENTO_ACTUAL = "MOVIMIENTO_ACTUAL";
export const ACTUALIZAR_MOVIMIENTO = "ACTUALIZAR_MOVIMIENTO";
export const LIMPIAR_MOVIMIENTO = "LIMPIAR_MOVIMIENTO";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR= "REGISTRO_ERROR";
export const OBTENER_USUARIO= "OBTENER_USUARIO";
export const LOGIN_EXITOSO= "LOGIN_EXITOSO";
export const LOGIN_ERROR= "LOGIN_ERROR";
export const CERRAR_SESION= "CERRAR_SESION";






